dataset_configs:
    - dataset_name: npn
      observations_data_file: ./cleaned_data/NPN_observations.csv
      temp_data_file: ./cleaned_data/npn_temp.csv
      add_site_dummy_var: False
    - dataset_name: harvard
      observations_data_file: ./cleaned_data/harvard_observations.csv
      temp_data_file: ./cleaned_data/harvard_temp.csv
      add_site_dummy_var: True

models_to_use:
    - uniforc

num_bootstrap: 500

model_parameter_file: ./results/model_parameters.csv
