dataset_configs:
    - dataset_name: npn
      observations_data_file: ./cleaned_data/npn_observations.csv
      temp_data_file: ./cleaned_data/npn_temp.csv
      add_site_dummy_var: False
    - dataset_name: harvard
      observations_data_file: ./cleaned_data/harvard_observations.csv
      temp_data_file: ./cleaned_data/harvard_temp.csv
      add_site_dummy_var: False
    - dataset_name: jornada
      observations_data_file: ./cleaned_data/jornada_observations.csv
      temp_data_file: ./cleaned_data/jornada_temp.csv
      add_site_dummy_var: False
    - dataset_name: hubbard
      observations_data_file: ./cleaned_data/hubbardbrook_observations.csv
      temp_data_file: ./cleaned_data/hubbard_temp.csv
      add_site_dummy_var: False
    - dataset_name: rmbl
      observations_data_file: ./cleaned_data/rmbl_observations.csv
      temp_data_file: ./cleaned_data/rmbl_temp.csv
      add_site_dummy_var: False

models_to_use:
    - uniforc

num_bootstrap: 500

model_parameter_file: ./results/model_parameters.csv
